## Runtime dynamic loader for wolfSSL using softlink.
## Only compiled when -d:wolfsslStatic is NOT defined.
##
## Provides:
##   wolfsslAvailable*() — true if the library is loaded
##
## Generated by softlink:
##   loadWolfssl(), wolfsslLoaded(), unloadWolfssl()

import softlink
import wolfssl/ssl

export softlink

# wolfSSL requires options.h before ssl.h for feature flags (TLS 1.3, SNI, etc.)
{.emit: """/*INCLUDESECTION*/
#include <wolfssl/options.h>
""".}

# Cross-platform library patterns.
when defined(macosx):
  const wolfsslPattern = "libwolfssl(.43|.42|.41|.40|.39|.38|.37|.36|.35|).dylib"
elif defined(windows):
  const wolfsslPattern = "wolfssl.dll"
else:
  const wolfsslPattern = "libwolfssl.so(.43|.42|.41|.40|.39|.38|.37|.36|.35|)"

dynlib wolfsslPattern:
  # Init/cleanup
  proc wolfSSL_Init(): cint {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_Cleanup(): cint {.cdecl, header: "<wolfssl/ssl.h>".}

  # Method selection
  proc wolfTLSv1_2_client_method(): ptr WolfsslMethod {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfTLSv1_3_client_method(): ptr WolfsslMethod {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSLv23_client_method(): ptr WolfsslMethod {.cdecl, header: "<wolfssl/ssl.h>".}

  # Context
  proc wolfSSL_CTX_new(meth: ptr WolfsslMethod): ptr WolfsslCtx {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_CTX_free(ctx: ptr WolfsslCtx) {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_CTX_load_verify_locations(ctx: ptr WolfsslCtx, file, path: cstring): cint {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_CTX_load_verify_buffer(ctx: ptr WolfsslCtx, buf: ptr byte, sz: clong, format: cint): cint {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_CTX_set_verify(ctx: ptr WolfsslCtx, mode: cint, cb: pointer) {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_CTX_SetMinVersion(ctx: ptr WolfsslCtx, version: cint): cint {.cdecl, header: "<wolfssl/ssl.h>".}

  # Client certificate / mTLS
  proc wolfSSL_CTX_use_certificate_file(ctx: ptr WolfsslCtx, file: cstring, format: cint): cint {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_CTX_use_PrivateKey_file(ctx: ptr WolfsslCtx, file: cstring, format: cint): cint {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_CTX_use_certificate_buffer(ctx: ptr WolfsslCtx, buf: ptr byte, sz: clong, format: cint): cint {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_CTX_use_PrivateKey_buffer(ctx: ptr WolfsslCtx, buf: ptr byte, sz: clong, format: cint): cint {.cdecl, header: "<wolfssl/ssl.h>".}

  # Session
  proc wolfSSL_new(ctx: ptr WolfsslCtx): ptr Wolfssl {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_free(ssl: ptr Wolfssl) {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_set_fd(ssl: ptr Wolfssl, fd: cint): cint {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_connect(ssl: ptr Wolfssl): cint {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_shutdown(ssl: ptr Wolfssl): cint {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_write(ssl: ptr Wolfssl, data: pointer, sz: cint): cint {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_read(ssl: ptr Wolfssl, data: pointer, sz: cint): cint {.cdecl, header: "<wolfssl/ssl.h>".}

  # SNI and hostname verification
  proc wolfSSL_UseSNI(ssl: ptr Wolfssl, typ: cint, data: pointer, size: cushort): cint {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_check_domain_name(ssl: ptr Wolfssl, dn: cstring): cint {.cdecl, header: "<wolfssl/ssl.h>".}

  # ALPN
  proc wolfSSL_UseALPN(ssl: ptr Wolfssl, protocols: cstring, sz: cuint, options: uint8): cint {.cdecl, header: "<wolfssl/ssl.h>".}

  # Peer certificate
  proc wolfSSL_get_peer_certificate(ssl: ptr Wolfssl): ptr WolfsslX509 {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_X509_get_der(x509: ptr WolfsslX509, outSz: ptr cint): ptr byte {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_X509_free(x509: ptr WolfsslX509) {.cdecl, header: "<wolfssl/ssl.h>".}

  # Error
  proc wolfSSL_get_error(ssl: ptr Wolfssl, ret: cint): cint {.cdecl, header: "<wolfssl/ssl.h>".}
  proc wolfSSL_ERR_error_string(err: culong, buf: cstring): cstring {.cdecl, header: "<wolfssl/ssl.h>".}

proc wolfsslAvailable*(): bool = wolfsslLoaded()
